import { useState, useEffect } from 'react';
import { useAuth } from '../providers/AuthProvider';
import { motion } from 'framer-motion';
import { Users, Play, Heart, Gift, Music2 } from 'lucide-react';

interface PoolItem {
  id: number;
  generation_id: string;
  quality: string;
  genre: string;
  plays: number;
  likes: number;
  audio_url: string;
  contributed_at: string;
  contributor: {
    user_id: string;
    username: string;
    avatar: string;
  };
}

export default function CommunityPool() {
  const { user, userTier } = useAuth();
  const [poolItems, setPoolItems] = useState<PoolItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [claiming, setClaiming] = useState(false);

  const backendUrl = import.meta.env.VITE_BACKEND_URL || 'http://localhost:3001';

  useEffect(() => {
    fetchPool();
  }, []);

  const fetchPool = async () => {
    try {
      const response = await fetch(`${backendUrl}/api/community/pool?limit=50&sort_by=recent`);
      if (response.ok) {
        const data = await response.json();
        setPoolItems(data.items || []);
      }
    } catch (error) {
      console.error('Error fetching pool:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleClaim = async () => {
    if (!user?.id) return;
    
    setClaiming(true);
    try {
      const response = await fetch(`${backendUrl}/api/community/pool/claim`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ user_id: user.id })
      });

      if (response.ok) {
        const data = await response.json();
        alert(`Claimed! Audio: ${data.audio_url}`);
        fetchPool();
      } else {
        const error = await response.json();
        alert(error.detail || 'Failed to claim');
      }
    } catch (error) {
      console.error('Error claiming:', error);
    } finally {
      setClaiming(false);
    }
  };

  const isFree = userTier?.tier === 'FREE';

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-3xl font-bold text-white flex items-center gap-3">
            <Users className="w-8 h-8 text-cian" />
            Community Pool
          </h1>
          <p className="text-gray-400 mt-2">
            Free music generated by paid members
          </p>
        </div>

        {isFree && (
          <button
            onClick={handleClaim}
            disabled={claiming}
            className="px-6 py-3 bg-gradient-to-r from-cian to-magenta text-white rounded-lg font-bold hover:shadow-lg transition-all disabled:opacity-50"
          >
            {claiming ? 'Claiming...' : (
              <>
                <Gift className="w-5 h-5 inline mr-2" />
                Claim Free Track
              </>
            )}
          </button>
        )}
      </div>

      {isFree && (
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-6 p-4 bg-carbón-dark border border-cian/20 rounded-lg"
        >
          <p className="text-white">
            🎁 <strong>FREE users:</strong> Claim 3 tracks per day from the community pool!
          </p>
        </motion.div>
      )}

      {loading ? (
        <div className="flex justify-center py-12">
          <div className="w-8 h-8 border-2 border-cian border-t-transparent rounded-full animate-spin" />
        </div>
      ) : poolItems.length === 0 ? (
        <div className="text-center py-12 bg-carbón-dark rounded-xl">
          <Music2 className="w-12 h-12 text-gray-600 mx-auto mb-4" />
          <p className="text-gray-400">Pool is empty</p>
          <p className="text-sm text-gray-500 mt-2">Check back later!</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {poolItems.map((item, index) => (
            <motion.div
              key={item.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.05 }}
              className="bg-carbón-dark border border-cian/20 rounded-xl overflow-hidden"
            >
              <div className="p-4">
                <div className="flex items-center gap-3 mb-3">
                  <img
                    src={item.contributor.avatar}
                    alt={item.contributor.username}
                    className="w-8 h-8 rounded-full"
                  />
                  <div>
                    <p className="text-white text-sm font-medium">
                      {item.contributor.username}
                    </p>
                    <p className="text-xs text-gray-400">
                      {new Date(item.contributed_at).toLocaleDateString()}
                    </p>
                  </div>
                  <span className="ml-auto px-2 py-1 bg-cian/20 text-cian text-xs rounded">
                    {item.quality}
                  </span>
                </div>

                {item.audio_url && (
                  <audio controls className="w-full mb-3">
                    <source src={item.audio_url} />
                  </audio>
                )}

                <div className="flex items-center justify-between text-sm">
                  <div className="flex items-center gap-4 text-gray-400">
                    <span className="flex items-center gap-1">
                      <Play className="w-4 h-4" />
                      {item.plays}
                    </span>
                    <span className="flex items-center gap-1">
                      <Heart className="w-4 h-4" />
                      {item.likes}
                    </span>
                  </div>
                  {item.genre && (
                    <span className="text-cian">{item.genre}</span>
                  )}
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
}
