"""
Harmonic Alignment Module (HAM v2)
A modular system for aligning sections from different generative AI models

This module provides tools for ensuring musical coherence when combining
audio sections generated by different AI music models (e.g., MusicGen,
HeartMuLa, AudioLDM2).

Key Components:
- Key Detection v1: Basic musical key analysis
- Key Detection v2: Robust multi-method key detection with confidence
- Chord Detection: Chord progression analysis
- BPM Detection v1: Basic tempo detection
- BPM Detection v2: Multi-method ensemble with beat tracking
- Energy Profile: RMS energy normalization
- Spectral Match: Spectral characteristic matching
- Stitcher v1: Basic crossfade concatenation
- Stitcher v2: Advanced harmonic-aware transitions

The main entry point is the HarmonicAlignmentEngine class which
orchestrates all alignment steps in the correct order.

Example Usage:
    from alignment import HarmonicAlignmentEngine, create_alignment_engine
    from alignment import RobustKeyDetector, RobustBPMDetector, ChordDetector

    # Create engine with default settings
    engine = create_alignment_engine(sr=44100)

    # Analyze a section
    analysis = engine.analyze_section(audio, sr)
    print(f"Key: {analysis['key']['name']}, BPM: {analysis['bpm']['value']}")

    # Robust key detection (v2)
    key_detector = RobustKeyDetector()
    key_result = key_detector.detect_key(audio, sr)
    print(f"Key: {key_result.key_name} (conf: {key_result.confidence:.2f})")

    # Robust BPM detection (v2)
    bpm_detector = RobustBPMDetector()
    bpm_result = bpm_detector.detect_bpm(audio, sr)
    print(f"BPM: {bpm_result.bpm:.1f} (stability: {bpm_result.tempo_stability:.2f})")

    # Chord progression analysis
    chord_detector = ChordDetector()
    progression = chord_detector.detect_progression(audio, sr)
    for chord in progression.chords:
        print(f"{chord.time:.1f}s: {chord.chord}")

    # Align a section to match a reference
    aligned = engine.align_section(reference_audio, section_audio, sr)

    # Full pipeline: align and stitch multiple sections
    sections = [intro, verse, chorus, verse, chorus, outro]
    final_track = engine.full_pipeline(sections, reference_index=0)

Performance Notes:
- All operations are CPU-based (no GPU required)
- Memory efficient: targets <2GB RAM usage
- Suitable for real-time preview and batch processing
"""

from .harmonic_alignment import (
    HarmonicAlignmentEngine,
    AlignmentConfig,
    AlignmentResult,
    create_alignment_engine,
)

from .key_detection import (
    detect_key,
    detect_key_with_confidence,
    compute_semitone_shift,
    pitch_shift_audio,
    get_key_name,
    estimate_mode,
    KEY_NAMES,
)

from .key_detection_v2 import (
    RobustKeyDetector,
    KeyDetectionResult,
    MAJOR_PROFILE,
    MINOR_PROFILE,
)

from .chord_detection import (
    ChordDetector,
    ChordDetectionResult,
    ChordProgression,
)

from .bpm_detection import (
    detect_bpm,
    detect_bpm_confidence,
    compute_time_stretch_ratio,
    time_stretch_audio,
    quantize_bpm,
    detect_bpm_with_beats,
    snap_to_grid,
)

from .bpm_detection_v2 import (
    RobustBPMDetector,
    BPMDetectionResult,
)

from .energy_profile import (
    compute_rms_energy,
    compute_rms_envelope,
    normalize_energy,
    match_energy,
    compute_loudness_range,
    apply_fade,
    compute_peak_energy,
    soft_clip,
)

from .spectral_match import (
    compute_spectral_centroid,
    compute_spectral_bandwidth,
    compute_spectral_rolloff,
    compute_spectral_flatness,
    get_spectral_profile,
    apply_spectral_adjustment,
    match_spectral_profile,
)

from .stitcher import (
    crossfade,
    concatenate_with_crossfade,
    butt_splice,
    beat_synced_crossfade,
    trim_silence,
    pad_to_length,
)

from .stitcher_v2 import (
    AdvancedStitcher,
    CrossfadeConfig,
    SplicePoint,
)

__version__ = "2.0.0"
__author__ = "SON1KVERS3 Research Lab"

__all__ = [
    # Main engine
    "HarmonicAlignmentEngine",
    "AlignmentConfig",
    "AlignmentResult",
    "create_alignment_engine",
    # Key detection v1
    "detect_key",
    "detect_key_with_confidence",
    "compute_semitone_shift",
    "pitch_shift_audio",
    "get_key_name",
    "estimate_mode",
    "KEY_NAMES",
    # Key detection v2
    "RobustKeyDetector",
    "KeyDetectionResult",
    "MAJOR_PROFILE",
    "MINOR_PROFILE",
    # Chord detection
    "ChordDetector",
    "ChordDetectionResult",
    "ChordProgression",
    # BPM detection v1
    "detect_bpm",
    "detect_bpm_confidence",
    "compute_time_stretch_ratio",
    "time_stretch_audio",
    "quantize_bpm",
    "detect_bpm_with_beats",
    "snap_to_grid",
    # BPM detection v2
    "RobustBPMDetector",
    "BPMDetectionResult",
    # Energy profile
    "compute_rms_energy",
    "compute_rms_envelope",
    "normalize_energy",
    "match_energy",
    "compute_loudness_range",
    "apply_fade",
    "compute_peak_energy",
    "soft_clip",
    # Spectral match
    "compute_spectral_centroid",
    "compute_spectral_bandwidth",
    "compute_spectral_rolloff",
    "compute_spectral_flatness",
    "get_spectral_profile",
    "apply_spectral_adjustment",
    "match_spectral_profile",
    # Stitcher v1
    "crossfade",
    "concatenate_with_crossfade",
    "butt_splice",
    "beat_synced_crossfade",
    "trim_silence",
    "pad_to_length",
    # Stitcher v2
    "AdvancedStitcher",
    "CrossfadeConfig",
    "SplicePoint",
]
