"""
Harmonic Alignment Module (HAM v1)
Main engine for aligning sections from different generative models

This module provides a complete pipeline for aligning audio sections
generated by different AI models (e.g., MusicGen, HeartMuLa) before
final stitching and mastering.

Key Features:
- Key detection and pitch alignment
- BPM detection and time-stretch alignment
- Energy normalization
- Spectral matching
- Clean section stitching

The HAM system improves hybrid model coherence by ensuring that
sections generated by different models share consistent musical
characteristics before being combined into a final track.

Usage:
    from alignment import HarmonicAlignmentEngine

    engine = HarmonicAlignmentEngine(sr=44100)
    aligned = engine.align_section(base_audio, section_audio, sr)
"""

import numpy as np
import librosa
from typing import Optional, Dict, Any, Tuple, List
from dataclasses import dataclass
import gc

from .key_detection import (
    detect_key,
    detect_key_with_confidence,
    compute_semitone_shift,
    pitch_shift_audio,
    get_key_name,
)
from .bpm_detection import (
    detect_bpm,
    detect_bpm_with_confidence,
    compute_time_stretch_ratio,
    time_stretch_audio,
    quantize_bpm,
)
from .energy_profile import compute_rms_energy, normalize_energy, match_energy
from .spectral_match import (
    compute_spectral_centroid,
    apply_spectral_adjustment,
    get_spectral_profile,
)
from .stitcher import crossfade, concatenate_with_crossfade, trim_silence


@dataclass
class AlignmentConfig:
    """Configuration for harmonic alignment processing."""

    enable_key_alignment: bool = True
    enable_bpm_alignment: bool = True
    enable_energy_alignment: bool = True
    enable_spectral_alignment: bool = True

    max_pitch_shift_semitones: int = 6
    max_time_stretch_ratio: float = 0.15
    target_energy: float = 0.15
    spectral_adjustment_intensity: float = 0.5

    crossfade_duration: float = 2.0
    fade_curve: str = "logarithmic"

    min_bpm: float = 60.0
    max_bpm: float = 200.0

    verbose: bool = True


@dataclass
class AlignmentResult:
    """Result of alignment processing."""

    aligned_audio: np.ndarray
    original_key: int
    target_key: int
    key_shift: int
    original_bpm: float
    target_bpm: float
    time_stretch_ratio: float
    original_energy: float
    aligned_energy: float
    spectral_adjustment_applied: bool
    processing_time: float
    warnings: List[str]


class HarmonicAlignmentEngine:
    """
    Main engine for harmonic alignment of audio sections.

    This class provides a complete pipeline for aligning sections
    from different generative models to ensure musical coherence
    when stitching them together.

    The alignment process includes:
    1. Key detection and pitch shifting
    2. BPM detection and time stretching
    3. Energy normalization
    4. Spectral matching

    Example:
        >>> engine = HarmonicAlignmentEngine()
        >>> aligned_section = engine.align_section(
        ...     base_audio=verse,
        ...     section_audio=chorus,
        ...     sr=44100
        ... )
    """

    def __init__(self, sr: int = 44100, config: Optional[AlignmentConfig] = None):
        """
        Initialize the Harmonic Alignment Engine.

        Args:
            sr: Sample rate for all processing. Default: 44100
            config: Optional alignment configuration
        """
        self.sr = sr
        self.config = config or AlignmentConfig()
        self._memory_usage = 0

        if self.config.verbose:
            print(f"[HAM] Harmonic Alignment Engine initialized")
            print(f"[HAM] Sample rate: {sr} Hz")
            print(f"[HAM] Key alignment: {self.config.enable_key_alignment}")
            print(f"[HAM] BPM alignment: {self.config.enable_bpm_alignment}")

    def align_section(
        self,
        base_audio: np.ndarray,
        section_audio: np.ndarray,
        sr: Optional[int] = None,
    ) -> np.ndarray:
        """
        Align a section to match the base audio's characteristics.

        This is the main method that applies all alignment steps
        to prepare a section for seamless stitching.

        Args:
            base_audio: Reference audio to match
            section_audio: Audio to be aligned
            sr: Sample rate (uses engine default if not specified)

        Returns:
            Aligned section ready for stitching

        Raises:
            ValueError: If audio arrays are empty or invalid
        """
        import time

        start_time = time.time()

        sr = sr or self.sr

        self._validate_inputs(base_audio, section_audio)

        section = section_audio.copy().astype(np.float32)
        warnings = []

        if self.config.verbose:
            print(f"\n[HAM] Starting alignment process...")
            print(f"[HAM] Base audio length: {self._get_duration(base_audio):.2f}s")
            print(f"[HAM] Section length: {self._get_duration(section):.2f}s")

        try:
            if self.config.enable_key_alignment:
                section, key_info = self._align_key(base_audio, section, sr)
                if self.config.verbose and key_info["shift"] != 0:
                    print(f"[HAM] Key aligned: {key_info['shift']:+d} semitones")
            else:
                key_info = {"shift": 0}

            if self.config.enable_bpm_alignment:
                section, bpm_info = self._align_bpm(base_audio, section, sr)
                if self.config.verbose:
                    print(f"[HAM] BPM aligned: {bpm_info['ratio']:.3f}x")
            else:
                bpm_info = {"ratio": 1.0}

            if self.config.enable_energy_alignment:
                section = self._align_energy(base_audio, section)
                if self.config.verbose:
                    print(f"[HAM] Energy aligned")

            if self.config.enable_spectral_alignment:
                section = self._align_spectral(base_audio, section, sr)
                if self.config.verbose:
                    print(f"[HAM] Spectral characteristics matched")

            section = trim_silence(section, sr, threshold_db=-50.0)

            self._cleanup_memory()

            processing_time = time.time() - start_time
            if self.config.verbose:
                print(f"[HAM] Alignment complete in {processing_time:.2f}s")

            return section

        except Exception as e:
            warnings.append(f"Alignment error: {str(e)}")
            if self.config.verbose:
                print(f"[HAM] Warning: {e}")
            return section_audio.copy()

    def align_sections(
        self,
        sections: List[np.ndarray],
        reference_index: int = 0,
        sr: Optional[int] = None,
    ) -> List[np.ndarray]:
        """
        Align multiple sections to a common reference.

        Args:
            sections: List of audio sections to align
            reference_index: Index of section to use as reference
            sr: Sample rate

        Returns:
            List of aligned sections
        """
        if not sections:
            raise ValueError("Sections list cannot be empty")

        if reference_index < 0 or reference_index >= len(sections):
            reference_index = 0

        reference = sections[reference_index]
        aligned = []

        for i, section in enumerate(sections):
            if i == reference_index:
                aligned.append(section.copy())
            else:
                aligned.append(self.align_section(reference, section, sr))

        return aligned

    def stitch_sections(
        self,
        sections: List[np.ndarray],
        crossfade_duration: Optional[float] = None,
        sr: Optional[int] = None,
    ) -> np.ndarray:
        """
        Stitch multiple aligned sections together.

        Args:
            sections: List of aligned audio sections
            crossfade_duration: Duration of crossfades (uses config if not specified)
            sr: Sample rate

        Returns:
            Combined audio with smooth transitions
        """
        sr = sr or self.sr
        fade_duration = crossfade_duration or self.config.crossfade_duration

        if not sections:
            raise ValueError("Sections list cannot be empty")

        if self.config.verbose:
            print(f"\n[HAM] Stitching {len(sections)} sections...")
            print(f"[HAM] Crossfade duration: {fade_duration:.2f}s")

        return concatenate_with_crossfade(
            sections, sr, fade_duration=fade_duration, apply_fade_edges=True
        )

    def full_pipeline(
        self,
        sections: List[np.ndarray],
        reference_index: int = 0,
        sr: Optional[int] = None,
    ) -> np.ndarray:
        """
        Complete pipeline: align all sections and stitch together.

        This is the highest-level method that handles the entire
        hybrid generation workflow.

        Args:
            sections: List of audio sections from different models
            reference_index: Index of reference section
            sr: Sample rate

        Returns:
            Final combined audio track
        """
        sr = sr or self.sr

        if self.config.verbose:
            print(f"\n[HAM] Full pipeline started")
            print(f"[HAM] Processing {len(sections)} sections")

        aligned = self.align_sections(sections, reference_index, sr)

        result = self.stitch_sections(aligned, sr=sr)

        if self.config.verbose:
            duration = self._get_duration(result)
            print(f"[HAM] Pipeline complete: {duration:.2f}s output")

        return result

    def analyze_section(
        self, audio: np.ndarray, sr: Optional[int] = None
    ) -> Dict[str, Any]:
        """
        Analyze a section's musical characteristics.

        Returns comprehensive information about key, BPM, energy,
        and spectral characteristics.

        Args:
            audio: Audio to analyze
            sr: Sample rate

        Returns:
            Dictionary with analysis results
        """
        sr = sr or self.sr

        key_idx, key_conf = detect_key_with_confidence(audio, sr)
        bpm, bpm_conf = detect_bpm_with_confidence(audio, sr)
        energy = compute_rms_energy(audio)
        spectral = get_spectral_profile(audio, sr)

        return {
            "key": {
                "index": key_idx,
                "name": get_key_name(key_idx),
                "confidence": key_conf,
            },
            "bpm": {"value": round(bpm, 1), "confidence": bpm_conf},
            "energy": {"rms": energy},
            "spectral": spectral,
            "duration": self._get_duration(audio),
        }

    def _align_key(
        self, base: np.ndarray, section: np.ndarray, sr: int
    ) -> Tuple[np.ndarray, Dict]:
        """Align section key to base audio."""
        base_key = detect_key(base, sr)
        section_key = detect_key(section, sr)

        shift = compute_semitone_shift(section_key, base_key)

        if abs(shift) > self.config.max_pitch_shift_semitones:
            if self.config.verbose:
                print(
                    f"[HAM] Pitch shift {shift} exceeds max {self.config.max_pitch_shift_semitones}, clamping"
                )
            shift = int(np.sign(shift) * self.config.max_pitch_shift_semitones)

        if shift != 0:
            section = pitch_shift_audio(section, sr, shift)

        return section, {
            "base_key": base_key,
            "section_key": section_key,
            "shift": shift,
        }

    def _align_bpm(
        self, base: np.ndarray, section: np.ndarray, sr: int
    ) -> Tuple[np.ndarray, Dict]:
        """Align section BPM to base audio."""
        base_bpm = detect_bpm(
            base, sr, min_bpm=self.config.min_bpm, max_bpm=self.config.max_bpm
        )
        section_bpm = detect_bpm(
            section, sr, min_bpm=self.config.min_bpm, max_bpm=self.config.max_bpm
        )

        ratio = compute_time_stretch_ratio(
            section_bpm, base_bpm, max_stretch=self.config.max_time_stretch_ratio
        )

        if ratio != 1.0:
            section = time_stretch_audio(section, sr, ratio)

        return section, {
            "base_bpm": base_bpm,
            "section_bpm": section_bpm,
            "ratio": ratio,
        }

    def _align_energy(self, base: np.ndarray, section: np.ndarray) -> np.ndarray:
        """Align section energy to base audio."""
        target_energy = compute_rms_energy(base)

        if target_energy < 0.001:
            target_energy = self.config.target_energy

        return normalize_energy(section, target_energy)

    def _align_spectral(
        self, base: np.ndarray, section: np.ndarray, sr: int
    ) -> np.ndarray:
        """Match section spectral characteristics to base."""
        target_centroid = compute_spectral_centroid(base, sr)

        return apply_spectral_adjustment(
            section,
            sr,
            reference_centroid=target_centroid,
            intensity=self.config.spectral_adjustment_intensity,
        )

    def _validate_inputs(self, base: np.ndarray, section: np.ndarray):
        """Validate input audio arrays."""
        if base is None or base.size == 0:
            raise ValueError("Base audio cannot be empty")
        if section is None or section.size == 0:
            raise ValueError("Section audio cannot be empty")

    def _get_duration(self, audio: np.ndarray) -> float:
        """Get audio duration in seconds."""
        if audio.ndim == 2:
            return audio.shape[1] / self.sr
        return len(audio) / self.sr

    def _cleanup_memory(self):
        """Clean up memory after processing."""
        gc.collect()


def create_alignment_engine(
    sr: int = 44100,
    max_pitch_shift: int = 6,
    max_stretch: float = 0.15,
    crossfade_duration: float = 2.0,
    verbose: bool = True,
) -> HarmonicAlignmentEngine:
    """
    Factory function to create a configured alignment engine.

    Args:
        sr: Sample rate
        max_pitch_shift: Maximum semitones to pitch shift
        max_stretch: Maximum time stretch ratio
        crossfade_duration: Crossfade duration in seconds
        verbose: Enable verbose output

    Returns:
        Configured HarmonicAlignmentEngine instance
    """
    config = AlignmentConfig(
        max_pitch_shift_semitones=max_pitch_shift,
        max_time_stretch_ratio=max_stretch,
        crossfade_duration=crossfade_duration,
        verbose=verbose,
    )

    return HarmonicAlignmentEngine(sr=sr, config=config)


if __name__ == "__main__":
    print("=" * 60)
    print("  HARMONIC ALIGNMENT MODULE (HAM v1)")
    print("  Hybrid Model Coherence for AI Music Generation")
    print("=" * 60)

    sr = 44100
    duration = 5.0

    t = np.linspace(0, duration, int(sr * duration))

    base_freq = 261.63
    section_freq = 329.63

    base_audio = 0.3 * np.sin(2 * np.pi * base_freq * t)
    section_audio = 0.4 * np.sin(2 * np.pi * section_freq * t)

    print("\n[TEST] Creating alignment engine...")
    engine = create_alignment_engine(sr=sr, verbose=True)

    print("\n[TEST] Analyzing base audio...")
    base_analysis = engine.analyze_section(base_audio, sr)
    print(f"  Duration: {base_analysis['duration']:.2f}s")
    print(
        f"  Key: {base_analysis['key']['name']} (conf: {base_analysis['key']['confidence']:.2f})"
    )
    print(
        f"  BPM: {base_analysis['bpm']['value']:.1f} (conf: {base_analysis['bpm']['confidence']:.2f})"
    )

    print("\n[TEST] Aligning section to base...")
    aligned = engine.align_section(base_audio, section_audio, sr)
    print(f"  Input length: {len(section_audio)} samples")
    print(f"  Output length: {len(aligned)} samples")

    print("\n[TEST] Stitching multiple sections...")
    sections = [base_audio, aligned, base_audio]
    combined = engine.stitch_sections(sections, sr=sr)
    print(f"  Combined length: {len(combined) / sr:.2f}s")

    print("\n[TEST] Full pipeline test...")
    test_sections = [
        0.3 * np.sin(2 * np.pi * 220 * t),
        0.4 * np.sin(2 * np.pi * 330 * t),
        0.3 * np.sin(2 * np.pi * 440 * t),
    ]
    final = engine.full_pipeline(test_sections, sr=sr)
    print(f"  Final output: {len(final) / sr:.2f}s")

    print("\n" + "=" * 60)
    print("  HAM v1 ready for integration with son1k-heart")
    print("=" * 60)
